node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') { // Make sure you have installed nodejs plugin in Jenkins and added in the global tool configurations
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') { // Configure credentials for dockerhub in Jenkins global credentials
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
       def app = docker.build("rounaksurana123/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
